services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: client-backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  db_data:
