version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: traders_uga
      MYSQL_USER: trader
      MYSQL_PASSWORD: traderpw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: client-backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:
