from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.db import get_session
from app.models.user import User
from app.schemas.user import UserCreate, UserOut, Token
from app.core.security import hash_password, verify_password, create_token

router = APIRouter(prefix="/auth", tags=["auth"])

@router.post("/signup", response_model=UserOut, status_code=201)
async def signup(payload: UserCreate, session: AsyncSession = Depends(get_session)):
    """
    @brief Register a new user account.

    Validates that the email is not already in use, hashes the password, persists
    the user, and returns the created user info.

    @param payload UserCreate The signup payload containing email and password.
    @param session AsyncSession Database session dependency.
    @return UserOut The created user with generated userId.
    @throws HTTPException 409 if the email is already registered.
    """
    # check if email already exists
    result = await session.execute(select(User).where(User.email == payload.email))
    existing = result.scalar_one_or_none()
    if existing:
        raise HTTPException(status_code=409, detail="Email already registered")

    # If email does not exist create new user
    user = User(
        email=payload.email,
        password=hash_password(payload.password)
    )

    # Stage and commit user to db
    session.add(user)
    await session.commit()
    await session.refresh(user)

    # Return user with userId generated by MySQL
    return UserOut(userId=user.userId, email=user.email)

@router.post("/login")
async def login(payload: UserCreate, session: AsyncSession = Depends(get_session)):
    """
    @brief Authenticate a user and issue an access token.

    @param payload UserCreate The login payload containing email and password.
    @param session AsyncSession Database session dependency.
    @return Token Access token for authenticated requests.
    @throws HTTPException 401 if credentials are invalid.
    """
    result = await session.execute(select(User).where(User.email == payload.email))
    user = result.scalar_one_or_none()

    # If user not found, or password is incorrect, throw error
    if not user or not verify_password(payload.password, user.password):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")
    
    token = create_token(subject=user.userId)
    return Token(access_token=token)
