from fastapi import APIRouter, Depends, HTTPException, status, Request, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.db import get_session
from app.models.user import User
from app.schemas.user import UserCreate, UserOut, Token
from app.core.security import hash_password, verify_password, create_token
from app.core.dependencies import get_user_from_refresh




router = APIRouter(prefix="/auth", tags=["auth"])

@router.post("/signup", response_model=UserOut, status_code=201)
async def signup(payload: UserCreate, session: AsyncSession = Depends(get_session)):
    # check if email already exists
    result = await session.execute(select(User).where(User.email == payload.email))
    existing = result.scalar_one_or_none()
    if existing:
        raise HTTPException(status_code=409, detail="Email already registered")

    # If email does not exist create new user
    user = User(
        email=payload.email,
        password=hash_password(payload.password)
    )

    # Stage and commit user to db
    session.add(user)
    await session.commit()
    await session.refresh(user)

    # Return user with userId generated by MySQL
    return UserOut(userId=user.userId, email=user.email)


@router.post("/login", response_model=Token)
async def login(payload: UserCreate, response: Response, session: AsyncSession = Depends(get_session)):

    result = await session.execute(select(User).where(User.email == payload.email))
    user = result.scalar_one_or_none()
    
    if not user or not verify_password(payload.password, user.password):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")
    
    access_token = create_token(subject=user.userId)
    refresh_token = create_token(subject=user.userId, refresh=True)
    
    token_data = Token(access_token=access_token)
    
    response.set_cookie(
        key="refresh",
        value=refresh_token,
        httponly=True,
        secure=True,
        max_age=3*24*3600, # 3 days
        samesite="none",
        path="/auth/refresh"
    )

    return token_data  


@router.post("/logout", status_code=204)
async def logout(response: Response):
    #Handles only the deletion of the refresh token, deletion of access token is done in the frontend client
    response.delete_cookie("refresh", path="/auth/refresh") 
    return None

@router.get("/refresh", response_model=Token)
async def refresh_access_token(request: Request, user = Depends(get_user_from_refresh)):

    if not user:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid refresh token")
    
    token = create_token(subject=user.userId)

    return Token(access_token=token)